const fs = require('fs');
const path = require('path');

// Create favicon.ico by copying a simple volcano emoji as base64
const faviconBase64 = `AAABAAEAICAAAAEAIACoEAAAFgAAACgAAAAgAAAAQAAAAAEAIAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkJCQQJCQkJCQkJCQkJCQkJCQkJCQkJCQkEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQkJDgkJCTAJCQlQCQkJZwkJCW4JCQluCQkJZwkJCVAJCQkwCQkJDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJCQkKCQkJH8kJCTRJCQk+SQkJP8kJCT/JCQk/yQkJP8kJCT5JCQk0SQkJH8kJCQoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJCQkHiQkJIckJCT1JCQk/yQkJP8kJCT/JCQk/yQkJP8kJCT/JCQk/yQkJP8kJCT1JCQkhyQkJB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAODg4CDg4OGM4ODjiODg4/zg4OP84ODj/ODg4/zg4OP84ODj/ODg4/zg4OP84ODj/ODg4/zg4OP84ODjiODg4Yzg4OAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE1NTQZMTEyGTExM/UxMTP9MTEz/TExM/0xMTP9MTEz/TExM/0xMTP9MTEz/TExM/0xMTP9MTEz/TExM/0xMTP9MTEyGTE1NBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgYGAqYGBg3WBgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYN1gYGAqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHR0dHN0dHT/dHR0/3R0dP90dHT/dHR0/3R0dP90dHT/dHR0/3R0dP90dHT/dHR0/3R0dP90dHT/dHR0/3R0dP90dHT/dHR0/3R0dHMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIiIgOiIiIyoiIiP+IiIj/iIiI/4iIiP+IiIj/iIiI/4iIiP+IiIj/iIiI/4iIiP+IiIj/iIiI/4iIiP+IiIj/iIiI/4iIiP+IiIj/iIiIyoiIiA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJycnDCcnJz5nJyc/5ycnP+cnJz/nJyc/5ycnP+cnJz/nJyc/5ycnP+cnJz/nJyc/5ycnP+cnJz/nJyc/5ycnP+cnJz/nJyc/5ycnP+cnJz/nJyc+ZycnDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsLCwULCwsP+wsLD/sLCw/7CwsP+wsLD/sLCw/7CwsP+wsLD/sLCw/7CwsP+wsLD/sLCw/7CwsP+wsLD/sLCw/7CwsP+wsLD/sLCw/7CwsP+wsLD/sLCw/7CwsFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsqKhmrKio/6yoqP+sqKj/rKio/6yoqP+sqKj/rKio/6yoqP+sqKj/rKio/6yoqP+sqKj/rKio/6yoqP+sqKj/rKio/6yoqP+sqKj/rKio/6yoqP+sqKj/rKio/6yoqGYAAAAAAAAAAAAAAAAAAAAAAAAAAKCYmG6gmJj/oJiY/6CYmP+gmJj/oJiY/6CYmP+gmJj/oJiY/6CYmP+gmJj/oJiY/6CYmP+gmJj/oJiY/6CYmP+gmJj/oJiY/6CYmP+gmJj/oJiY/6CYmP+gmJj/oJiY/6CYmG4AAAAAAAAAAAAAAAAAAAAAlIiIbpSIiP+UiIj/lIiI/5SIiP+UiIj/lIiI/5SIiP+UiIj/lIiI/5SIiP+UiIj/lIiI/5SIiP+UiIj/lIiI/5SIiP+UiIj/lIiI/5SIiP+UiIj/lIiI/5SIiP+UiIj/lIiI/5SIiG4AAAAAAAAAAAAAAACEeHhmhHh4/4R4eP+EeHj/hHh4/4R4eP+EeHj/hHh4/4R4eP+EeHj/hHh4/4R4eP+EeHj/hHh4/4R4eP+EeHj/hHh4/4R4eP+EeHj/hHh4/4R4eP+EeHj/hHh4/4R4eP+EeHj/hHh4/4R4eGYAAAAAAAAAAHhoaFB4aGj/eGho/3hoaP94aGj/eGho/3hoaP94aGj/eGho/3hoaP94aGj/eGho/3hoaP94aGj/eGho/3hoaP94aGj/eGho/3hoaP94aGj/eGho/3hoaP94aGj/eGho/3hoaP94aGj/eGho/3hoaP94aGhQAAAAAGxYWDBsWFj5bFhY/2xYWP9sWFj/bFhY/2xYWP9sWFj/bFhY/2xYWP9sWFj/bFhY/2xYWP9sWFj/bFhY/2xYWP9sWFj/bFhY/2xYWP9sWFj/bFhY/2xYWP9sWFj/bFhY/2xYWP9sWFj/bFhY/2xYWP9sWFj5bFhYMGBISA5gSEjKYEhI/2BISP9gSEj/YEhI/2BISP9gSEj/YEhI/2BISP9gSEj/YEhI/2BISP9gSEj/YEhI/2BISP9gSEj/YEhI/2BISP9gSEj/YEhI/2BISP9gSEj/YEhI/2BISP9gSEj/YEhI/2BISP9gSEj/YEhIymBISA5UODhzVDg4/1Q4OP9UODj/VDg4/1Q4OP9UODj/VDg4/1Q4OP9UODj/VDg4/1Q4OP9UODj/VDg4/1Q4OP9UODj/VDg4/1Q4OP9UODj/VDg4/1Q4OP9UODj/VDg4/1Q4OP9UODj/VDg4/1Q4OP9UODj/VDg4/1Q4OHNEKChqRCgo3UQoKP9EKCj/RCgo/0QoKP9EKCj/RCgo/0QoKP9EKCj/RCgo/0QoKP9EKCj/RCgo/0QoKP9EKCj/RCgo/0QoKP9EKCj/RCgo/0QoKP9EKCj/RCgo/0QoKP9EKCj/RCgo/0QoKP9EKCj/RCgo3UQoKGo4GBgGOBgYhjgYGP04GBj/OBgY/zgYGP84GBj/OBgY/zgYGP84GBj/OBgY/zgYGP84GBj/OBgY/zgYGP84GBj/OBgY/zgYGP84GBj/OBgY/zgYGP84GBj/OBgY/zgYGP84GBj/OBgY/zgYGP04GBiGOBgYBgAAAAAsCAghLAgI4iwICP8sCAj/LAgI/ywICP8sCAj/LAgI/ywICP8sCAj/LAgI/ywICP8sCAj/LAgI/ywICP8sCAj/LAgI/ywICP8sCAj/LAgI/ywICP8sCAj/LAgI/ywICP8sCAjiLAgIIQAAAAAAAAAAAAAAACgAAB4oAAB1KAAAuSgAAOUoAAD1KAAA+SgAAP8oAAD/KAAA/ygAAP8oAAD/KAAA/ygAAP8oAAD/KAAA/ygAAP8oAAD/KAAA+SgAAPUoAADlKAAAuSgAAHUoAAAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////4////+H////A////gH///wB///4Af//8AH//+AA///AAf//gAP//wAH//4AD//8AB///AAf//wAH//8AB///AAf//wAH//+AB///wAf//8AH///gB////Af///4H////D///////////////////////8=`;

// Write favicon.ico
const faviconPath = path.join(__dirname, '..', 'public', 'favicon.ico');
fs.writeFileSync(faviconPath, Buffer.from(faviconBase64, 'base64'));
console.log('Created favicon.ico');

// Create additional favicon sizes as PNG placeholders
const sizes = [
  { name: 'favicon-16x16.png', size: 16 },
  { name: 'favicon-32x32.png', size: 32 },
  { name: 'apple-touch-icon.png', size: 180 },
  { name: 'android-chrome-192x192.png', size: 192 },
  { name: 'android-chrome-512x512.png', size: 512 }
];

// Simple PNG generation (1x1 orange pixel, scaled)
const createSimplePNG = (size) => {
  const PNG_SIGNATURE = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
  const IHDR = Buffer.concat([
    Buffer.from([0, 0, 0, 13]),
    Buffer.from('IHDR'),
    Buffer.from([0, 0, 0, size]), // width
    Buffer.from([0, 0, 0, size]), // height
    Buffer.from([8, 2, 0, 0, 0]), // bit depth, color type, compression, filter, interlace
    Buffer.from([0, 0, 0, 0]) // CRC placeholder
  ]);
  
  return Buffer.concat([PNG_SIGNATURE, IHDR]);
};

sizes.forEach(({ name, size }) => {
  const filePath = path.join(__dirname, '..', 'public', name);
  // For now, create empty files as placeholders
  fs.writeFileSync(filePath, '');
  console.log(`Created placeholder for ${name}`);
});

console.log('All favicon files created successfully!');